### ISSUE TITLE
How is it possible use CUPS as client inside a docker container?

### ISSUE THREAD

**Issue by thiagolmoraes** [apple/cups#5866]
I have a application which uses lp command, by deploying it to a container I realized problems to print using CUPS.

Dockerfile:

```
FROM node:15

RUN apt-get update && \
    apt-get -y install cups cups-pdf

WORKDIR /app/

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8080

CMD ["npm","run","proxy"]  
```  
Docker-compose:

```
version: '3'
services:
  ambiente_teste_project:
    build: .  
    ports:
      - "8080:8080"
    container_name: teste_container
    volumes:
      - /var/run/cups/cups.sock:/var/run/cups/cups.sock
    
```
That attempt I got to run lp commands, this output is the same in my computer (Linux Ubuntu), both printers is working.

```
root@2911c9cd355e:/app# lpstat -p
printer CUPS-PDF-Printer is idle.  enabled since Wed Dec  9 21:40:59 2020
printer iR1730-1740-1750-UFRII-LT now printing iR1730-1740-1750-UFRII-LT-57.  enabled since Wed Dec  9 21:29:55 2020
        The printer is not responding.
```
Trying to print in both printer, I opened "Printers" at HostServer (Linux Ubuntu) and realized which none of printers is receiving any job.

`lp -o landscape -o fit-to-page -o media=A4 src/assets/large.pdf -d CUPS-PDF-Printer`

Anyone has suggestion to work Cups Client?
